using Common.Implementation.Device;
using Common.Interfaces.Device;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace UnitTests.Mocks.Device
{
    public class MockDeviceAuthorizationRepository : IDeviceAuthorizationRepository
    {
        private string data = "EJVIRV TSHJUM VNUDET WZJXVB OSQFOM VGZAPG LPPJVO BDVOBG QARWNU YHMSQF EECFCD PAVUZJ SAZSRM ZOJIJU HHSJFK DMEHFQ SZMMJJ SHXFGT HXQFGJ IVTFOT UKJHCV XJGIZT DRPEZC ZSWTPL MVVNBO MPQLJJ QSVJPO BMCICF WOHNMW XMKFYI NNAVIT AFOEIW OBIKNS QRGSRD QLXUQD RUJXGF NCNRBW KZHWTT YAOXHD MREVXJ UTWBBW JTUYYV ZIMORL KXWCKH PUZQOB ZNAICJ GOQOQK VXOBQZ QERONM XVQIUH NTTAQU NFOCRG IELVMP GEVWVD FXIKCA IXFFTQ HSRMEF EQUEFK LZHXNZ BNUGWR IUDASM EQARNL XNUBXJ POVVVS LLCANH LQSSFN NKQIIP DLCYNQ LJFXMA BMZUPD ZNIHZY MHDMEM FANDWQ HBHZYV CODGEQ UQIEEI VUUQEX JWMYHN XUTXQT GFWYCQ ADTLFB PCCBMO JJDFJL JZYUET RZDACO TIGZRP FNVURZ AOPWUN ZJEVWM YDQIZO UYVQOI MLAHQC HVIOXV JTCXPS EAFYLS PPEGEB DCGLWK ABMORK RZSQKP LHBOCG MVRWDI WXVAJP ESMXTE OCDGIN CPXFCM LSLKZZ ARMHZM BNUBZL TBPNED PHAIGN OIAGXT KHLIEF QQRFAY PLYDUQ MNWDMW QOAWPX VPFMDE FLYJMR KNDKQG WULCVE ZTSVAH XHZMRV FSNDVK SQLDRR ZPYFSD TWVNYZ HRBLLA ZEEKCR HQMYBK UCCXPY ASTYDM UZNPTB BRWYSM TRQLJE KFNIHX TXNOIW NLDFTG RXABOI ZKRNCC NILXLM UAWNFX XINTPI BWYRJH SDYMDV SUHFMA NWANYN DSEZKT GJIPOS POTJRQ LZVKUD DDJNSA KZMZKE YXITXY KJNZPN TVVLJX SWZDBG FMCPEO OMJLTW NFZRNS YTGAGU OUCXKY YKCDOX ZJTDQF IXDUUA JPVMTO DQIYZP NLULFV AGBTXC OBCJVC LCRYKH COYBDV TNSDRS CRSZKN OHCJJQ YJLAJG BLPMSL KJBPJC POQSYK SEYKRU QTUPBP AJVCMW PUNIZP JLQVWE BWCUSV ZWUWQC VLMDLC GGJILV CRQMHA OVIQGG WDJCTH YLOCSF UVLETY NKEUAE LORULF QOMZKP CUPUPY TZIHAT SQMFHG PLFNEE ZSVWLF WGEBPM YUMEUV WJOTWK WEWXDF OEETLU POILBN AMGTUZ GQSVJE PXIPZD TZNAGZ WGHNUP GOKUFP DICHJD XZJEXX FBAEOZ KZBYLM MQKAXC XDQDFZ QBVGVX HVWGHN QFOYWQ NFZKAV QLSGRN AYBIXN QPUHRB TRCFLL XQYZBZ IHLPGC PACGYV ZBMDAG RGTTEZ QSFWDN ACSVXQ CZAQTA WSJNLW FOJOEI XUDNAN UUCSWF DHCHSN OBGNAT HCDQAG VYMDLY DVCFCC SWXCRO LRPRFQ USZYCY QUTYOM NRBMLT DFKOFS GZMMBI PHWNFW UXYUNX IADSTG VAGMFS FMQFCR KLZMIP TVUZYL SRQRVJ SALWWU SQLMAF QNVAOU EUMAWK HCGJDC YQGUSQ SFMCZE KRWNPO EMPKKP NXBZBE IEGXLS ONFURB QIBNCE WNXGXA OHTHAR GPOHMU UGFLAC IVPSFW TIQHZB UFXZJZ YKPGRV PZOIYD NTNPUR AKVAPQ WZXIJE OELFHI UWPMPP MSUNXO SNIAEK HHZZVZ DNKKBC ELIVOZ AUBCWN AUYRHL QVZYQM KCSZBX DSXWZV YCJHMN ZLEAGV KLPIBT GQDDMZ UGRFYR VGZCVB TPOYPT XYGMTJ NZPIMF QXEIIC MFCICT PFCRYF YMPZWU ECGYBK NHYZKL SROQSO OKXNVU LDMAOM ILTQWB RHSEFF FCZAYK BNKCHY SBSEHU IUMEAV SINIVW UDHFYY EJKOSD KSYQPG ZWGIKD IDADAT BMQJIU YYGYEG OEDRCZ LOWOAE TEYLBZ XOERGS IYRRAI UYWIXR HEKIMW XOBNRV YJCSUG UUBQVV NCSJUR XJLOPS YGEEUV QSCPCM RFEJQF QQIJEW IIXAHT CDUPLJ ZWDTKX HUQDQI BXPRVA CSRXON EWRYWJ XTZULK ZZBXSU HEDUVC SAPOGP MHOHUS PFRAWM TPUMRU CZIGTI FJIQFQ BPPLTP KZDWQI LWSVOI TMYZAK LQFNOU WYDMCB OJCOBR PWHULG UTOBRX MIGJSZ NOICTN APQTVZ BFUSZA NHKYOO OBSUWL LXNIEC DGVDOB ZPRCWJ WOZYBO PRGCRT OKTNNY XDRDBF KFYYEW TRAXFW AATIKY DQCHIK JDTEPZ CXOJNW SJECWQ RTIKGG TDDWTA LXKLGX HJVATO ARDQSG HPPWBE DILAFY ORLMLI RUIEWD PGJQEE JANRRB FPBPMS TALUJV LOSJIE XYDTOI ZJFPIQ XYGVCH XFYSYO TPYOLW JDEKNZ BBGUIW JKHJIX YRYZXN RGWFJS RAYQCR QUTOQI JNLZFL JAZYOD SXAEVT RHCZWY KEIYGG FOYWIH RVZYUC WQYLEB LWLUFR VZUYSO WECRWK ENPOXE WSNRXO VTABDU RUPDNF OQARUQ BKBBHM GEQDOE TXRCHJ XLKUSZ GXPDEG OIBOAZ ZBULNY DXBPKM EGWNYI TDAHAV VTPZLG DDHCST EMWYYE RBLZNT OMFHMV EYVJIH IAMLKW DFTKXQ ATDNME XBFCNU QTLLZP IPOIEN DZMLKF NKSXFM PGEAYZ MCBDUL THMJLL FVNZXG CCXMDW FRWNFL JGKZFZ HKTUWC JZIKIH BWEZHG AWRXKZ YTAMZI GXAMXD LRDDNI AMCSCP ONYBQF TJVVNP XZURVI UCSVAB KBIAGF RASYTE DWHEQV NSDYTX LNEMYJ SYTGEE QQCQNB DFLMAB TSVZGL SZGFRM FTWLPE FUGGAA JOKPPO LVESWJ WEODUP MSHPJA EDIRRF QGQENJ DVWMXP NSQWLX EFAEXK NNCXXR BWNNLC TCHTGY WGFIWS NJFUPN JFBXJF YBIOHG YMMVNC DAVZKU GMRZBT GMZGVG QSYVXO QRAELA LBVKLL BEVMXK UBZYNR XJNMYS YEKITN RKSZHV ZEPQOX UFNLSB SKRZVJ QOLGPA SPFXBH ZXYJSP PZFVTO MSWOHQ YORUMS NRATKH JKBAYR BPTLAM WWKLRV EGYJWS CFXUVO EGDLXV EBHHFN JWZUTC LPIMVP IIHUJY QECTEO DFGTDV CMWKSI IGXHLK TUDFWU PHNBVZ OMPXMP MJNKBN AIYCGY JYHWGO LDBCQZ QPDWBP EIQRWC TFSHWF NISSCN TJSVKK TBIBWK SYASFN WOQEMG LDCLTR NOFQOI NXPWYY HDENKQ YOQXNJ VWOVYU RQZEES ASDWLS MUZCHE RVFDJV FTVIDH IFJBOR NMPHRH ZFFLTJ SNXWCJ VMKLCY UUDPAT VCDSBI XXYIOY QRHVDU ZHGKZY GSTQJG JXCAXD WRCTDX QYYIHD QBOWJI YGWULJ MLBGNT YYMQCA RUOEUS GNEKIY ABSYQG REGRSV KEMLXQ HRYZSC LBCJCO YERMCX HDHYLY PODYIU DVWDZH TLAFDN MFHSLJ HQGGOB ESQPJC LPBNQC BFECFN VJSRTJ RJGUPR RTNMYT LSYQCE NPUTDI ZCAUPZ IVLTFN CTJVYK OBQTDB MJLLIS SBVAOI TPKTHC UTOJTV XVUOKR DGRVBR XUBIEC GQWWON EFKYCF ZMXQFF HSIJND DVFGYS AULGTB BZWJAS XZCGQZ FETMOG EDHSZL XBEQEN QZZJBH FPQXHV EXHCJK YAYJMI LICXPF ZQWDLZ HCZHHR LXZMFM PQLJNZ IEYSZW KYRURB OQEPFP JPCABO BCGSZG JPHKSL JYZOJA XUAHCD OGZKEH KTIYYJ NTIKLN ZQLXKE DLUNKD OTIVFF KUTTOI BMRFNE CHCIWX YLYGRK PZEOXW RFNJPO RDVYAX LOUQGE FRJLUR EAFJKZ HNIKFC IVNEXC QJRRQJ ZNSYCX BLJUQI YAWIZO RBSFIZ YRVADP QMLVMN VURQAX IFWJIC QEFTXV SPEVUZ YSEHGN CNEHDH WSFKYT UAXJGZ DRETFE RGUJFL KDGKNQ AOKGME QUMRKP FLFVWE CDSREB YUYTYE DQFAQC KTUCXZ ODZRRW SWPLXA GCFKKQ TBWJWL PQTVMX IBXQGQ RDMENK VKXDVB BBVAJS PLWLRP TTRUTB MMRWVS NARXAH AGSJIO XSNZIG KCODHO DLVJSK NYOHQX TKVKER LUNSCS JCBIHB MWRETM AQXSQM XBBHXM KQWYJY RCDPQH XGTVWE PIPRFB IDILBS LONXQF KAIAJV NVCULU RHZKCF PEOTPI TPNYBN HCKSQZ XELZXM YOGFBJ YGKHJO WEUHXO OLBMXU QJMPMZ DSXAEM ZJPBZO NAUPPO EOYSYB GCQDSS ETNUSZ LPEQMR FJHXOB NWHHBU MJCUQW LCVUUX PCGGBT SGRENI XYOETD FDNVDM FKGPYH IMAQDN SJEHAY VBDLFV JNVSOG HPBTMX HWJYFP WMWDNZ VJUORO JFDQZO ZBCRWC BEBPBQ PXMLRM NMOEUC ENSTCZ WSZQGB REYIML LDTNKF BAMYMZ LHICML LPJRBB NHEEWO XUBIDB VOLSPR TLFBIC TNGHCF APXQXV EGAKED WTSUWO RVXHTT DTAPWY LWHIYK RZNOBU TGJRZT DRDDIX IHNPPQ GMUNRN YXROII RZONAK PEBYCM GTBGUD QNUHTR WUURKY PCXFEV SYMVGV UCKLEP FTSIFT HLYTSJ TXBGWH QCXKAV OFDHLF GGSERK PMOXBH MRVCEJ ZHACTS CSEENH GOYSIS IABURW FMSXGL NUJEUN BHXYDR UYOVJQ GIHXOZ NZRRDX QADJZS STRROZ URYKAQ TXHRER WUKWJQ SQEOEF YKAWPN DLKQJI MZELRJ ZOYEQO SFUSXD PTESBJ VKEPUC LQQJYD GJOZDB ETJUQO YTCLVK WVHPCI AIEAFT HGDGTG SKRRJO WZHKPE WNTWCS YSVKYX QBCVOJ UCUWTX GFZPMO NFQADG WPVGHA VAXLSH ETTSDE PHNZJN AIZIPE JBDMNJ QWYMAF JXRKFT PRXYGU WSZYEJ NRSCZH RFHELT CMNJKS PJFNDZ PKHBBU ARAING RTOLUS GPHDHT TESDBI MXQTYU QWAKDL WJGXXA EHOUFH PUPQDA ABWCNC XGGSIT NOKKMA HYPENA MTHMFM LBTPRU RXSSIY EICAYL CHVZYQ KDUIWQ OXLNNN JBYCDD DJXVHA OHWVUV IWMUFC QDPMRZ GPSNHO TUYZCI WWUAOO DIQYDO YPHSMC XKTCVF UHCZUS AXGHWY AAJZXJ HMYCFI YJBKTS SUEVVJ CVYWEK LPSPCA ZMBDWH LQJFOR HJFCEF MGUYSG VIRHJT JTROGG GEFPRN TFDQHI IKATGL RKHFGM KPTFST YGYVZZ VNLLBI EKFRSH DGQVXT UPXEWS ONBHRG DXRNSE QQSKSU IMRPMO TQTEST XPOVRQ KCRMVE JOMONW LIBUMH QQBUVS IWITLK PHUAJP YJTBYX KICNDF WMZUJP JCGZPC RBOPOI PXXKOB TTKOMN HABCQF ZYOPYN VTNADA ZPKDGQ KFVJPY BJWLFS WMWJSQ DUVQKV POPWPS CCOROE KKIBIH REFXVC UVVTDF SCTRRA TLINSN RWRSSN RTMJZS BEXULF AAHLYT UJLCDQ RHGNFC UJJKRB GGZNAI GBRCCR SYFYYG LRUNGK HJZOPS IJYSZY LPSCZH JRIZAS IQQENL VEJVRV DDYFSO IIOVQW CPRXEW XOVEZP CLILHK TKRTLR RTPWJE OFBSNI CIZPLY XRQMBL IAHNAV PSNVHG DXDSNZ FPUDKG SHZURS STBJML TLHNNK XTLRQU UAKNAY JSXIKZ VIPTIN HFDZVJ MMEXXI OMUARS EUJMJF IFKGPW DIKMLD DNZNFN VVKIBC XOYJYM LBDYWL PEDNUT YHJIUW IILUGC RTWSHL CUZDJR TYLXKW NDHSPR VZLHND ATYQYR FWOXMU YQWVND YLWTCY QCDPQP SEXILT";
        private int currentCode = 0;
        private string[] codes;
        List<IDeviceAuthorizationCode> authCodes;

        public MockDeviceAuthorizationRepository()
        {
            codes = data.Split(" ");
        }

        public string CreateAuthorizationCodeForDevice(Guid deviceId)
        {
            var authCode = new DeviceAuthorizationCode()
            {
                DeviceId = deviceId,
                Code = codes[currentCode++]
            };

            authCodes.Add(authCode);
            return authCode.Code;
        }

        public IDeviceAuthorizationCode GetItem(string key)
        {
            return authCodes.Where(c => c.Code == key).FirstOrDefault();
        }

        public void InvalidateAuthorizationCodeForDevice(Guid deviceId)
        {
            authCodes.RemoveAll(c => c.DeviceId == deviceId);
        }

        public IDeviceAuthorizationCode UpdateItem(IDeviceAuthorizationCode model)
        {
            var dbCode = GetItem(model.Code);

            if (dbCode != null)
            {
                dbCode.DateVerified = model.DateVerified;
            }

            return dbCode;
        }
    }
}
